name: BoboBot

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # Change these values if you have forked it for your own works
  GitHubMail: "adameyyad999@gmail.com"
  GitHubName: "nnippon" 

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Setup docker
        run: |
          brew install --cask virtualbox
          brew install --formula docker docker-machine
      - name: Setup VM
        run: |
          curl -sL https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso -o ~/Downloads/boot2docker.iso
          docker-machine create -d virtualbox --virtualbox-disk-size=200000 --virtualbox-memory=8096 --virtualbox-cpu-count=2 --virtualbox-boot2docker-url ~/Downloads/boot2docker.iso default
          docker-machine env default
      - name: Clone ErfanGSIs Repository
        run: |
          git clone --recurse-submodules https://github.com/nnippon/ErfanGSIs
          bash ErfanGSIs/setup.sh
      - name: Generate config.prop
        continue-on-error: true
        timeout-minutes: 3
        run: |
              java -jar Bobo.jar
      - name: Add values
        continue-on-error: true
        timeout-minutes: 1
        run: |
             rm -rf configs/config.prop && rm -rf configs/sf-creds.config
             cd configs
             touch config.prop
             echo "#Bo³+t config file" >> "config.prop"
             echo "#Sun Jan 10 09:00:49 Jer 2021" >> "config.prop"
             echo "bot-username=${{ secrets.BOTUN }}" >> "config.prop"
             echo "bot-token=${{ secrets.BOTKEY }}" >> "config.prop"
             echo "bot-master=${{ secrets.USERKEY }}" >> "config.prop"
             echo "bot-submaster=${{ secrets.SUBKEY }}" >> "config.prop"
             touch sf-creds.config
             echo "#Config file" >> "sf-creds.config"
             echo "#Sun Jan 10 09:00:49 Jer 2021" >> "sf-creds.config"
             echo "bot-sf-user=${{ secrets.SFUSER }}" >> "sf-creds.config"
             echo "bot-send-announcement=true" >> "sf-creds.config"
             echo "bot-sf-proj=${{ secrets.PROJECT }}" >> "sf-creds.config"
             echo "bot-announcement-id=-1001446520361" >> "sf-creds.config"
             echo "bot-sf-pass=${{ secrets.SFPASS }}" >> "sf-creds.config"
             echo "bot-sf-host=frs.sourceforge.net" >> "sf-creds.config"
      - name: Run Bot
        continue-on-error: true
        timeout-minutes: 300
        run: |
              sudo chmod -R 0777 *
              sudo java -jar Bobo.jar
      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
